name: Go Cross-Compile

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.4'

    - name: Build for Linux (x86_64)
      run: GOOS=linux GOARCH=amd64 go build -o bin/spotitunes-linux .

    - name: Build for Windows (x86_64)
      run: GOOS=windows GOARCH=amd64 go build -o bin/spotitunes-windows.exe .

    - name: Build for macOS M1 (ARM64)
      run: GOOS=darwin GOARCH=arm64 go build -o bin/spotitunes-macos-arm64 .

    - name: Upload All Binaries
      uses: actions/upload-artifact@v4
      with:
        name: myapp-binaries
        path: bin/
